/// Uzbek (Latin) buyer strings — copied verbatim from `i18n/uz_latn.ts`.
/// Placeholders look like `{name}`; substitute them with [t].
library;

const Map<String, String> uzLatn = {
  // ---- navigation ----
  'nav.home': 'Bosh sahifa',
  'nav.shops': 'Doʻkonlar',
  'nav.promotions': 'Aksiyalar',
  'nav.cart': 'Savat',
  'nav.orders': 'Buyurtmalar',
  'nav.profile': 'Profil',
  'nav.aria': 'Asosiy navigatsiya',

  // ---- common ----
  'common.all': 'Hammasi',
  'common.back': 'Orqaga',
  'common.cancel': 'Bekor qilish',
  'common.close': 'Yopish',
  'common.continue': 'Davom etish',
  'common.delete': 'Oʻchirish',
  'common.edit': 'Oʻzgartirish',
  'common.errorTitle': 'Nimadir xato ketdi',
  'common.errorText':
      'Maʼlumotni yuklab boʻlmadi. Internetni tekshirib, qayta urinib koʻring.',
  'common.less': 'Kamaytirish',
  'common.more': 'Koʻpaytirish',
  'common.retry': 'Qayta urinish',
  'common.save': 'Saqlash',

  'confirm.replaceCart.title': 'Savatni yangilaysizmi?',
  'confirm.replaceCart.text':
      'Savatingizda «{shop}» doʻkonining mahsulotlari bor. Bir buyurtmada faqat bitta doʻkondan xarid qilish mumkin. Yangi mahsulotni qoʻshsangiz, savat tozalanadi.',
  'confirm.replaceCart.yes': 'Ha, yangilash',

  // ---- onboarding ----
  'onb.welcome.title': 'Yaqin doʻkonlar, bir bosishda',
  'onb.welcome.b1': 'Atrofingizdagi doʻkonlarni koʻring',
  'onb.welcome.b2': 'Aksiya va chegirmalarni bir joyda toping',
  'onb.welcome.b3': 'Yetkazib berish yoki olib ketishni oʻzingiz tanlang',
  'onb.welcome.cta': 'Boshlash',
  'onb.terms.before': 'Davom etish orqali rozilik bildirasiz:',
  'onb.terms.and': '·',
  'onb.phone.title': 'Telefon raqamingiz',
  'onb.phone.text': 'Doʻkon buyurtma boʻyicha siz bilan bogʻlanishi uchun kerak.',
  'onb.phone.share': 'Raqamni ulashish',
  'onb.phone.manual': 'Raqamni qoʻlda kiritish',
  'onb.phone.label': 'Telefon raqami',
  'onb.phone.invalid': 'Raqam notoʻgʻri. Operator kodini tekshiring',
  'onb.phone.shareFailed': 'Raqam ulashilmadi. Uni qoʻlda kiriting',
  'onb.name.title': 'Ismingiz nima?',
  'onb.name.text': 'Doʻkon buyurtmani sizga shu ism bilan tayyorlaydi.',
  'onb.name.label': 'Ismingiz',
  'onb.name.invalid': 'Ism 2 dan 30 tagacha belgidan iborat boʻlsin',
  'onb.address.title': 'Manzilingiz qayerda?',
  'onb.address.text':
      'Yaqin atrofdagi doʻkonlarni koʻrsatish uchun manzilingiz kerak.',
  'onb.address.manual': 'Qoʻlda kiritish',
  'onb.address.done': 'Tayyor',
  'onb.outside.title': 'Bu hududga hali yetib bormadik',
  'onb.outside.text':
      'Hozircha faqat Chilonzor tumani va uning atrofida ishlaymiz. {district} tumanida ochilganda sizga xabar beramizmi?',
  'onb.outside.wait': 'Ha, xabar bering',
  'onb.outside.browse': 'Baribir koʻrish',
  'onb.waitlistDone': 'Rahmat! Hudud ochilganda xabar beramiz.',

  // ---- address ----
  'address.sheetTitle': 'Manzilni tanlang',
  'address.add': 'Manzil qoʻshish',
  'address.edit': 'Manzilni tahrirlash',
  'address.max': 'Eng koʻpi {n} ta manzil saqlash mumkin',
  'address.detect': 'Joylashuvimni aniqlash',
  'address.detected': 'Joylashuv aniqlandi. Koʻcha va uyni yozing',
  'address.detectFailed': 'Joylashuvni aniqlab boʻlmadi. Manzilni qoʻlda kiriting',
  'address.labelTitle': 'Manzil turi',
  'address.label.home': 'Uy',
  'address.label.work': 'Ish',
  'address.label.other': 'Boshqa',
  'address.district': 'Tuman',
  'address.street': 'Koʻcha va uy',
  'address.streetPlaceholder': 'Masalan, Bunyodkor koʻchasi, 12-uy',
  'address.apartment': 'Xonadon',
  'address.landmark': 'Moʻljal',
  'address.landmarkPlaceholder': 'Masalan, doʻkon yonida',
  'address.tooShort': 'Manzilni toʻliqroq yozing',

  // ---- home ----
  'home.deliverTo': 'Yetkazib berish manzili',
  'home.changeAddress': 'Manzilni oʻzgartirish',
  'home.pickAddress': 'Manzilni tanlang',
  'home.noAddress': 'Manzil tanlanmagan',
  'home.searchPlaceholder': 'Mahsulot yoki doʻkon qidiring',
  'home.searchHint': 'Nima kerak? Masalan: sut, non',
  'home.categoriesTitle': 'Turkumlar',
  'home.clearFilter': 'Filtrni olib tashlash',
  'home.categories': 'Turkumlar',
  'home.todayPromos': 'Bugungi aksiyalar',
  'home.nearbyShops': 'Yaqin doʻkonlar',
  'home.noShops': 'Hozircha atrofingizda doʻkon yoʻq',
  'home.otherAddress': 'Boshqa manzilni tanlash',
  'home.noShopsInCategory': 'Bu turkumda hozircha doʻkon yoʻq',
  'home.showAll': 'Hammasini koʻrsatish',

  'home.greeting': 'Assalomu alaykum!',
  'home.greetingSub': 'Bugun nimani xarid qilamiz?',
  'home.script': 'Yaqin doʻkonlardan tez va oson!',
  'home.city': 'Toshkent',
  'home.district': '{d} tumani',
  'home.searchHint2': 'Mahsulot yoki doʻkon qidirish...',
  'home.filter': 'Turkum boʻyicha saralash',
  'home.notifications': 'Buyurtmalar',
  'home.banner1.title': 'Bugungi aksiyalar',
  'home.banner1.text': 'Sevimli mahsulotlaringiz endi arzonroq!',
  'home.banner1.cta': 'Xarid qilish',
  'home.banner2.title': 'Issiq non, yangi sut',
  'home.banner2.text': 'Mahalla doʻkonlaridan tez yetkazib beramiz.',
  'home.banner2.cta': 'Koʻrish',
  'home.shopsTitle': 'Doʻkonlar',
  'home.seeAll': 'Barchasini koʻrish',
  'home.popular': 'Ommabop mahsulotlar',
  'home.fav.add': 'Sevimlilarga qoʻshish',
  'home.fav.remove': 'Sevimlilardan olib tashlash',
  'shops.title': 'Doʻkonlar',
  'shops.sub': 'Yaqin atrofdagi doʻkonlar',

  // ---- orders history + tracking ----
  'orders.title': 'Buyurtmalar tarixi',
  'orders.sub': 'Buyurtmalaringizni kuzating va boshqaring',
  'orders.tab.all': 'Barchasi',
  'orders.tab.done': 'Yetkazilgan',
  'orders.tab.active': 'Jarayonda',
  'orders.tab.closed': 'Bekor',
  'orders.sortTitle': 'Saralash',
  'orders.sort.newest': 'Yangilari birinchi',
  'orders.sort.oldest': 'Eskilari birinchi',
  'orders.sort.priciest': 'Qimmatlari birinchi',
  'orders.itemsCount': '{n} ta mahsulot',
  'orders.emptyFiltered': 'Bu boʻlimda buyurtma yoʻq',
  'trk.title': 'Buyurtma kuzatuvi',
  'trk.sub': 'Buyurtmangizni real vaqtda kuzating',
  'trk.shop': 'Doʻkon',
  'trk.eta': 'Taxminiy yetkazish',
  'trk.etaMin': '{n} daqiqa',
  'trk.today': 'Bugun, {t}',
  'trk.pickupWhere': 'Olib ketish manzili',
  'trk.payment': 'Toʻlov',
  'trk.itemsTitle': 'Buyurtma tarkibi',
  'trk.notFound': 'Buyurtma topilmadi',
  'trk.step.new': 'Yangi',
  'trk.step.accepted': 'Qabul qilindi',
  'trk.step.preparing': 'Yigʻilmoqda',
  'trk.step.on_the_way': 'Yoʻlda',
  'trk.step.ready': 'Tayyor',
  'trk.step.completed': 'Yetkazildi',
  'trk.step.pickedUp': 'Olib ketildi',
  'trk.msg.new.title': 'Buyurtma yuborildi',
  'trk.msg.new.text': 'Doʻkon tasdiqlashini kutyapmiz.',
  'trk.msg.accepted.title': 'Doʻkon buyurtmani qabul qildi',
  'trk.msg.accepted.text': 'Mahsulotlar tez orada yigʻiladi.',
  'trk.msg.preparing.title': 'Mahsulotlar yigʻilmoqda',
  'trk.msg.preparing.text': 'Doʻkon buyurtmangizni tayyorlayapti.',
  'trk.msg.on_the_way.title': 'Buyurtmangiz yoʻlda!',
  'trk.msg.on_the_way.text': 'Doʻkon yetkazib berishni boshladi.',
  'trk.msg.ready.title': 'Buyurtmangiz tayyor',
  'trk.msg.ready.text': 'Doʻkonga kelib olib ketishingiz mumkin.',
  'trk.msg.completed.title': 'Yoqimli ishtaha!',
  'trk.msg.completed.text': 'Xarid uchun rahmat.',
  'trk.msg.rejected.title': 'Doʻkon buyurtmani qabul qila olmadi',
  'trk.msg.cancelled.title': 'Buyurtma bekor qilindi',
  'trk.msg.cancelled.text': 'Istasangiz, boshqa doʻkondan buyurtma bering.',
  'trk.msg.expired.title': 'Doʻkon javob bermadi',
  'trk.msg.expired.text':
      'Buyurtma bekor qilindi. Boshqa doʻkonlardan buyurtma bering.',

  // ---- checkout ----
  'co.title': 'Buyurtma berish',
  'co.sub': 'Doʻkondan mahsulotlarga buyurtma bering',
  'co.script': 'Siz buyurtma bering, biz yetkazamiz!',
  'co.address': 'Yetkazib berish manzili',
  'co.enterAddress': 'Manzilingizni kiriting',
  'co.savedAddress': 'Saqlangan manzillardan tanlash',
  'co.products': 'Mahsulotlar',
  'co.note': 'Doʻkonga izoh',
  'co.notePh': 'Doʻkon uchun izoh (masalan: pishgan pomidor bering)',
  'co.fee': 'Yetkazib berish narxi',
  'co.distance': 'Masofa: {km}',
  'co.pickupInfo': 'Oʻzingiz olib ketasiz',
  'co.method': 'Toʻlov usuli',
  'co.online': 'Onlayn toʻlov',
  'co.soon': 'Tez orada',
  'co.cash': 'Naqd pul',
  'co.safe': 'Doʻkon qabul qilguncha buyurtmani bekor qilishingiz mumkin',
  'co.confirm': 'Buyurtmani tasdiqlash',

  // ---- shop ----
  'shop.open': 'Ochiq',
  'shop.closed': 'Yopiq',
  'shop.closedOpens': 'Yopiq · {time}',
  'shop.pickupOnly': 'Faqat olib ketish',
  'shop.promoCount': '{n} ta aksiya',
  'shop.distance': 'Masofa',
  'shop.time': 'Yetkazish vaqti',
  'shop.fee': 'Yetkazish narxi',
  'shop.free': 'Bepul',
  'shop.minOrder': 'Eng kam buyurtma: {sum}',
  'shop.closedBanner': 'Doʻkon hozir yopiq. {time}',
  'shop.closedBannerNoTime': 'Doʻkon vaqtincha yopiq.',
  'shop.noProducts': 'Bu turkumda mahsulot yoʻq',
  'shop.notFound': 'Doʻkon topilmadi',
  'shop.cartBar': 'Savat · {n} ta',

  // ---- product ----
  'product.addAria': 'Savatga qoʻshish: {name}',
  'product.addToCart': 'Savatga',
  'product.goToCart': 'Savatga oʻtish',
  'product.outOfStock': 'Tugagan',
  'product.shopClosed': 'Doʻkon yopiq',

  // ---- search ----
  'search.startTitle': 'Nimani qidiryapsiz?',
  'search.startText': 'Mahsulot yoki doʻkon nomini yozing',
  'search.minChars': 'Kamida {n} ta belgi kiriting',
  'search.clear': 'Tozalash',
  'search.recent': 'Oxirgi qidiruvlar',
  'search.clearRecent': 'Tozalash',
  'search.shops': 'Doʻkonlar',
  'search.products': 'Mahsulotlar',
  'search.sortLabel': 'Saralash',
  'search.sort.distance': 'Eng yaqin',
  'search.sort.price': 'Eng arzon',
  'search.sort.discount': 'Eng katta chegirma',
  'search.empty': '“{q}” boʻyicha hech narsa topilmadi',
  'search.emptyHint': 'Boshqa soʻz bilan urinib koʻring yoki imloni tekshiring.',

  // ---- promotions ----
  'promos.summary': 'Atrofingizdagi doʻkonlarda hozir {n} ta chegirma bor',
  'promos.empty': 'Hozircha aksiyalar yoʻq',
  'promos.emptyText':
      'Atrofingizdagi ochiq doʻkonlarda hozircha chegirmalar yoʻq.',

  // ---- cart ----
  'cart.empty': 'Savat boʻsh',
  'cart.browse': 'Doʻkonlarni koʻrish',
  'cart.from': 'Doʻkon',
  'cart.fulfilment': 'Qanday olasiz?',
  'cart.delivery': 'Yetkazib berish',
  'cart.pickup': 'Oʻzim olaman',
  'cart.noDelivery': 'Bu doʻkon yetkazib bermaydi — faqat olib ketish mumkin.',
  'cart.outOfRadius':
      'Manzilingiz doʻkonning yetkazib berish hududidan tashqarida.',
  'cart.address': 'Yetkazish manzili',
  'cart.change': 'Oʻzgartirish',
  'cart.payment': 'Toʻlov usuli',
  'cart.cash': 'Naqd',
  'cart.onlineSoon': 'Click, Payme, Uzum tez orada',
  'cart.comment': 'Izoh',
  'cart.commentPlaceholder': 'Doʻkon uchun izoh',
  'cart.items': 'Mahsulotlar',
  'cart.savings': 'Aksiyadan tejam',
  'cart.deliveryFee': 'Yetkazib berish narxi',
  'cart.total': 'Jami',
  'cart.order': 'Buyurtma berish · {sum}',
  'cart.placed': 'Buyurtma #{n} yuborildi',
  'cart.cannotOrder': 'Buyurtma berib boʻlmaydi',
  'cart.refresh': 'Savatni yangilash',
  'cart.refreshed': 'Savat yangilandi',
  'cart.whatChanged': 'Savatda oʻzgargan narsalar:',
  'cart.issue.closed': 'Doʻkon hozir yopiq',
  'cart.issue.closedAt': 'Doʻkon hozir yopiq ({time})',
  'cart.issue.minOrder':
      'Yetkazib berish uchun yana {sum} soʻmlik mahsulot qoʻshing',
  'cart.issue.outOfStock': '«{name}» tugab qoldi',
  'cart.issue.priceChanged': '«{name}» narxi oʻzgardi: {from} → {to}',
  'cart.issue.deliveryUnavailable':
      'Bu manzilga yetkazib berilmaydi. «Oʻzim olaman»ni tanlang',

  // ---- orders ----
  'orders.empty': 'Hozircha buyurtmalar yoʻq',
  'orders.emptyText': 'Birinchi buyurtmangizni bering — u shu yerda koʻrinadi.',
  'orders.callShop': 'Doʻkonga qoʻngʻiroq',
  'orders.cancel': 'Bekor qilish',
  'orders.cancelTitle': 'Buyurtmani bekor qilasizmi?',
  'orders.cancelText': '#{n} buyurtmani bekor qilmoqchimisiz?',
  'orders.cancelYes': 'Ha, bekor qilish',
  'orders.cancelNo': 'Yoʻq',
  'orders.cancelled': 'Buyurtma bekor qilindi',
  'orders.repeat': 'Takrorlash',
  'orders.repeated': '{n} ta mahsulot savatga qoʻshildi',
  'orders.repeatedPartial': '{n} ta mahsulot savatga qoʻshildi, {m} tasi tugagan',
  'orders.repeatNone': 'Mahsulotlar hozir mavjud emas',
  'orders.otherShops': 'Boshqa doʻkonlar',
  'orders.reason': 'Sabab: {reason}',
  'orders.expiredText':
      'Buyurtma bekor qilindi. Boshqa doʻkonlardan buyurtma bering.',
  'orders.more': 'yana {n} ta mahsulot',
  'orders.pickup': 'Olib ketish',

  // ---- order statuses ----
  'status.new': 'Yangi',
  'status.confirm': 'Tasdiqlash kerak',
  'status.accepted': 'Qabul qilindi',
  'status.preparing': 'Yigʻilmoqda',
  'status.on_the_way': 'Yoʻlda',
  'status.ready': 'Tayyor, olib keting',
  'status.delivered': 'Yetkazildi',
  'status.pickedUp': 'Olib ketildi',
  'status.rejected': 'Rad etildi',
  'status.cancelled': 'Bekor qilindi',
  'status.expired': 'Doʻkon javob bermadi',

  // ---- profile ----
  'profile.phone': 'Telefon',
  'profile.unverified': 'Tasdiqlanmagan',
  'profile.phoneChanged': 'Telefon raqami yangilandi',
  'profile.addresses': 'Manzillarim',
  'profile.default': 'Asosiy',
  'profile.makeDefault': 'Asosiy qilish',
  'profile.deleteAddressTitle': 'Manzilni oʻchirasizmi?',
  'profile.language': 'Til',
  'profile.languageValue': 'Oʻzbekcha (lotin)',
  'profile.help': 'Yordam',
  'profile.terms': 'Foydalanish shartlari',
  'profile.privacy': 'Maxfiylik siyosati',
  'profile.delete': 'Hisobni oʻchirish',
  'profile.deleteTitle': 'Hisobni oʻchirasizmi?',
  'profile.deleteText':
      'Shaxsiy maʼlumotlaringiz oʻchiriladi. Qonun talab qilgan maʼlumotlar bundan mustasno.',
  'profile.deleteYes': 'Ha, oʻchirish',

  // ---- legal (placeholders, must be reviewed by a lawyer) ----
  'legal.draft':
      'Namuna matn. Ishga tushirishdan oldin yurist tomonidan koʻrib chiqilishi kerak.',
  'legal.terms.1':
      'Yaqinda — atrofingizdagi doʻkonlarni koʻrish va ulardan buyurtma berish uchun Telegram mini-ilovasi.',
  'legal.terms.2':
      'Buyurtma tanlangan doʻkon bilan tuziladi; toʻlov hozircha naqd, yetkazib berish yoki olib ketish paytida amalga oshiriladi.',
  'legal.terms.3':
      'Buyurtmani doʻkon qabul qilguncha bekor qilish mumkin. Qabul qilingan buyurtmani faqat administrator bekor qila oladi.',
  'legal.privacy.1':
      'Ism, telefon raqami va manzilingiz faqat buyurtmani bajarish uchun ishlatiladi.',
  'legal.privacy.2':
      'Doʻkon sizning ismingiz, telefoningiz va manzilingizni faqat oʻzi qabul qilgan buyurtmalar boʻyicha, buyurtma yakunlangach 7 kun davomida koʻra oladi.',
  'legal.privacy.3':
      'Hisobni oʻchirsangiz, shaxsiy maʼlumotlaringiz oʻchiriladi (qonun saqlashni talab qiladiganlaridan tashqari).',

  // ---- design v4 ----
  'h.hello': 'Salom!',
  'h.hi': 'Salom, {name}',
  'h.deliverTo': 'Yetkazib berish manzili',
  'h.search': 'Doʻkon yoki mahsulot qidirish',
  'h.activeOrder': 'Buyurtma #{n}',
  'h.moreOrders': '+{n} ta faol buyurtma',
  'h.allShops': 'Hammasi',
  'h.promoCount': '{n} aksiya',
  'h.repeatTitle': 'Yana shuni buyurtma qilasizmi?',
  'h.repeatSub': '{shop} · {items}',
  'h.repeatCta': 'Takrorlash',
  'h.allProducts': 'Hammasini koʻrish',
  'h.perk1': 'Tez yetkazish',
  'h.perk1s': '20–35 daqiqada',
  'h.perk2': 'Naqd toʻlov',
  'h.perk2s': 'Qabul qilganda',
  'h.perk3': 'Yaqin doʻkonlar',
  'h.perk3s': 'Chilonzor',
  'h.inCart': 'Savatda: {n} ta',
  'h.title': 'Yaqin atrofingizdagi mahsulotlar',
  'h.shopsTitle': 'Doʻkonlar',
  'h.cats': 'Toifalar',
  'h.catOther': 'Boshqa',
  'h.shops': 'Yaqin doʻkonlar',
  'h.products': 'Mahsulotlar',
  'h.b1.title': 'Yangi imkoniyatlar siz uchun!',
  'h.b1.text': 'Sifatli mahsulotlar, qulay narxlarda',
  'h.b2.title': 'Bugungi aksiyalar',
  'h.b2.text': 'Sevimli mahsulotlaringiz endi arzonroq!',
  'h.b3.title': 'Issiq non, yangi sut',
  'h.b3.text': 'Mahalla doʻkonlaridan tez yetkazib beramiz.',
  'h.cta': 'Koʻrish',
  'hb.promo.tag': 'AKSIYA',
  'hb.promo.title': 'Ajoyib narxlar siz uchun!',
  'hb.promo.text': 'Sifatli mahsulotlar, har kuni yangi imkoniyatlar',
  'hb.promo.cta': 'Batafsil',
  'hb.fresh.tag': 'YANGI',
  'hb.fresh.title': 'Issiq non, yangi sut',
  'hb.fresh.text': 'Mahalla doʻkonlaridan tez yetkazib beramiz',
  'hb.fresh.cta': 'Doʻkonlar',
  'hb.fast.tag': 'TEZ',
  'hb.fast.title': 'Bir bosishda, eshigingizgacha',
  'hb.fast.text': 'Buyurtma bering, 20–35 daqiqada oling',
  'hb.fast.cta': 'Koʻrish',
  'out.title': 'Hozircha bu hududda yoʻqmiz',
  'out.text':
      'Hozir faqat Chilonzor tumanida ishlayapmiz. Tez orada sizga ham yetib boramiz.',
  'out.pick': 'Boshqa manzilni tanlash',
  'out.notify': 'Kelganimizda xabar bering',
  'out.address': 'Yetkazish manzili',
  'shops.search': 'Doʻkon nomini qidiring',
  'shops.count': '{n} ta doʻkon · eng yaqini birinchi',
  'shops.promos': '{n} ta aksiya',
  'shops.fee': 'Yetkazish {sum}',
  'shops.opensAt': '{time} da ochiladi',
  'shops.none': 'Doʻkon topilmadi',
  'sp.until': 'Ochiq · {time} gacha',
  'sp.min': 'Eng kami {sum}',
  'sp.fee': 'Yetkazish {sum}',
  'sp.promos': 'Aksiyalar',
  'sp.all': 'Barchasini koʻrish',
  'sp.soldout': 'Hozir tugagan',
  'sp.toCart': 'Savatga oʻtish',
  'sp.cartLine': 'Savat · {n} ta',
  'sp.pickupOnly': 'Faqat olib ketish',
  'sv.title': 'Savat',
  'sv.how': 'Qanday olasiz?',
  'sv.delivery': 'Yetkazib berish',
  'sv.pickup': 'Oʻzim olaman',
  'sv.free': 'Bepul',
  'sv.addr': 'Yetkazish manzili',
  'sv.landmark': 'Moʻljal: {v}',
  'sv.note': 'Doʻkon uchun izoh, masalan: domofon ishlamaydi',
  'sv.cash': 'Naqd pul',
  'sv.cashDelivery': 'Yetkazilganda toʻlaysiz',
  'sv.cashPickup': 'Olib ketganda toʻlaysiz',
  'sv.cardSoon': 'Karta orqali toʻlov tez orada',
  'sv.items': 'Mahsulotlar',
  'sv.saving': 'Aksiya chegirmasi',
  'sv.fee': 'Yetkazish',
  'sv.total': 'Jami',
  'sv.order': 'Buyurtma berish · {sum}',
  'sv.emptyTitle': 'Savat boʻsh',
  'sv.emptyText':
      'Yaqin doʻkonlardan mahsulot tanlang, 15–30 daqiqada eshigingizda.',
  'sv.emptyCta': 'Doʻkonlarni koʻrish',
  'sv.emptyPromos': 'Bugun atrofingizda {n} ta aksiya',
  'od.title': 'Buyurtmalar',
  'od.active': 'Faol',
  'od.previous': 'Oldingilar',
  'od.eta': '{a}–{b} orasida yetkaziladi',
  'od.details': 'Batafsil kuzatish',
  'od.itemsN': '{n} ta mahsulot',
  'od.repeat': 'Takrorlash',
  'od.emptyTitle': 'Hali buyurtma yoʻq',
  'od.emptyText': 'Birinchi buyurtmangizni bering, holatini shu yerda kuzatasiz.',
  'od.emptyCta': 'Xarid qilish',
  'ot.title': 'Buyurtma #{n}',
  'ot.help': 'Yordam',
  'ot.deliverBy': 'Doʻkonning oʻzi yetkazib beradi',
  'ot.pickupAt': 'Doʻkondan olib ketasiz',
  'ot.call': 'Qoʻngʻiroq',
  'ot.items': 'Buyurtma tarkibi',
  'ot.cashDelivery': 'Naqd pul, yetkazilganda',
  'ot.cashPickup': 'Naqd pul, olib ketilganda',
  'ot.address': 'Yetkazish manzili',
  'ot.step.accepted': 'Qabul qilindi',
  'ot.step.preparing': 'Yigʻilmoqda',
  'ot.step.on_the_way': 'Yoʻlda',
  'ot.step.ready': 'Tayyor',
  'ot.step.delivered': 'Yetkazildi',
  'ot.step.pickedUp': 'Olib ketildi',
  'pf.title': 'Profil',
  'pf.verified': 'Tasdiqlangan',
  'pf.edit': 'Tahrirlash',
  'pf.addresses': 'Mening manzillarim',
  'pf.addNew': 'Yangi manzil qoʻshish',
  'pf.ownerTitle': 'Doʻkoningiz bormi?',
  'pf.ownerText': 'Yaqindaga bepul qoʻshiling',
  'pf.version': 'Yaqinda 1.0',
  'pr.sorted': 'Eng katta chegirmalar birinchi',
  'pr.inCart': 'Savatda: {n}',
  'se.placeholder': 'Doʻkon yoki mahsulot qidirish',
  'se.summary': '“{q}” boʻyicha: {s} ta doʻkon, {p} ta mahsulot',
  'ps.qty': 'Miqdor',
  'ps.about': 'Mahsulot haqida',
  'ps.shopAbout': 'Doʻkon haqida',
  'ps.add': 'Savatga qoʻshish · {sum}',
  'ps.goShop': 'Doʻkonga oʻtish',
  'ps.promoUntil': 'Aksiya {when}',
  'cf.title': 'Savatni yangilaysizmi?',
  'cf.text':
      'Savatingizda {shop} mahsulotlari bor ({n} ta, {sum}). Bitta buyurtma faqat bitta doʻkondan boʻladi.',
  'cf.yes': 'Ha, yangi savat boshlash',
  'cf.no': 'Yoʻq, avvalgi savat qolsin',
  'cat.empty': 'Bu turkumda mahsulot topilmadi',
  'pc.title': 'Baʼzi mahsulotlar tugagan',
  'pc.text':
      '{shop} buyurtmangizni yigʻishga tayyor, lekin bitta mahsulot hozir yoʻq.',
  'pc.soldout': 'Tugagan',
  'pc.old': 'Avvalgi summa',
  'pc.new': 'Yangi summa',
  'pc.left': 'Javob berish uchun {t} qoldi',
  'pc.hint': 'Javob boʻlmasa, buyurtma bekor qilinadi.',
  'pc.confirm': 'Tasdiqlash · {sum}',
  'pc.cancel': 'Buyurtmani bekor qilish',
  'pc.review': 'Koʻrib chiqish',
  'trk.msg.confirm.title': 'Yangi summani tasdiqlang',
  'trk.msg.confirm.text': 'Doʻkonda bitta mahsulot tugabdi.',

  // ---- added for the Android demo (see DECISIONS.md) ----
  'support.title': 'Yordam',
  'support.text':
      'Savolingiz boʻlsa, Telegramdagi qoʻllab-quvvatlash hisobiga yozing.',
  'support.handle': '@YaqindaSupport',
  'support.copy': 'Nusxalash',
  'support.copied': 'Nusxalandi',
};

/// Looks up [key] and substitutes `{placeholder}` values from [params].
/// A missing key returns the key itself so nothing silently disappears.
String t(String key, [Map<String, Object?> params = const {}]) {
  var s = uzLatn[key] ?? key;
  params.forEach((k, v) {
    s = s.replaceAll('{$k}', '${v ?? ''}');
  });
  return s;
}
